### PR TITLE
Correctly populate github secret

### LINKED ISSUE #215: SDM local mode ignores token configuration value
When running in local mode, the `token` configuration value is ignored when cloning seed repositories.

```
✘ Command failure
Child process 32418 exited with non-zero status 128: . ==> git 'clone' 'https://undefined:x-oauth-basic@github.com/atomistxx/spring-rest.git' '/tmp/atm-32418-32418h308owt6hbZA'
Cloning into '/tmp/atm-32418-32418h308owt6hbZA'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://undefined:x-oauth-basic@github.com/atomistxx/spring-rest.git/'
```

### PR DESCRIPTION
**Pull request by cdupuis**
This will correctly use the token from the running client or configuration when invoking the command locally.

Fixes #215

### CODE REVIEW

File: lib/cli/invocation/http/invokeEventHandlerUsingHttp.ts [hunk 1]
```diff
@@ -63,10 +64,10 @@ export function invokeEventHandlerUsingHttp(location: AutomationClientConnection
                 correlation_id: target.correlationId || await newCliCorrelationId(),
             },
             secrets: (invocation.secrets || []).concat([
-                { uri: "github://user_token?scopes=repo,user:email,read:user", value: process.env.GITHUB_TOKEN },
-                { uri: "github://org_token", value: process.env.GITHUB_TOKEN },
-                { uri: Secrets.OrgToken, value: process.env.GITHUB_TOKEN },
-                { uri: Secrets.UserToken, value: process.env.GITHUB_TOKEN },
+                { uri: "github://user_token?scopes=repo,user:email,read:user", value: credentialsFromEnvironment().token },
```
Comment (ddgenome) [inline lib/cli/invocation/http/invokeEventHandlerUsingHttp.ts]: Optional optimization: call `credentialsFromEnvironment()` once, use many times.

File: lib/sdm/binding/EnvironmentTokenCredentialsResolver.ts [hunk 2]
```diff
@@ -47,7 +48,7 @@ export class EnvironmentTokenCredentialsResolver implements CredentialsResolver
 
 const DefaultGitHubToken = "not.a.real.token";
 
-function credentialsFromEnvironment(): ProjectOperationCredentials {
+export function credentialsFromEnvironment(): TokenCredentials {
     let token;
```
Comment (ddgenome) [inline lib/sdm/binding/EnvironmentTokenCredentialsResolver.ts]: Or you could cache it here.

File: lib/sdm/invocation/invokeEventHandlerInProcess.ts [hunk 3]
```diff
@@ -53,10 +54,10 @@ export function invokeEventHandlerInProcess(workspaceContext: LocalWorkspaceCont
                 correlation_id: correlationId || await newCliCorrelationId(),
             },
             secrets: (invocation.secrets || []).concat([
-                { uri: "github://user_token?scopes=repo,user:email,read:user", value: process.env.GITHUB_TOKEN },
-                { uri: "github://org_token", value: process.env.GITHUB_TOKEN },
-                { uri: Secrets.OrgToken, value: process.env.GITHUB_TOKEN },
-                { uri: Secrets.UserToken, value: process.env.GITHUB_TOKEN },
+                { uri: "github://user_token?scopes=repo,user:email,read:user", value: credentialsFromEnvironment().token },
```
Comment (ddgenome) [inline lib/sdm/invocation/invokeEventHandlerInProcess.ts]: Same

File: lib/cli/invocation/http/invokeEventHandlerUsingHttp.ts (hunk 1 above)
Comment (cdupuis) [reply lib/cli/invocation/http/invokeEventHandlerUsingHttp.ts]: Actually the results of calling `credentialsFromEnvironment` change over time. First time it is invoked the automation-client isn't up, hence the call to `configurationValue` will fail. I'm not sure what impact this might have on the various usages of the `CredentialsResolver` throughout. That's why I didn't change it to use caching.

Comment (cdupuis) [reply lib/cli/invocation/http/invokeEventHandlerUsingHttp.ts]: Ah, I see. yeah, I'll change that.
